#!/usr/bin/env python

from __future__ import print_function
import os, sys
import subprocess
from subprocess import Popen, CalledProcessError
import re
import tempfile
import time 
import shutil

from buildfarm import rosdistro

def parse_options():
    import argparse
    parser = argparse.ArgumentParser(description='Creates a set of source debs from a catkin gbp repo. Creates source debs from the latest upstream version.')
    parser.add_argument(dest='repo_uri',
            help='A read-only git buildpackage repo uri.')
    parser.add_argument('package_name', help='The package name for the package we\'re building')
    parser.add_argument('rosdistro', help='Which rosdistro to operate on')
    parser.add_argument('short_package_name', help='The package name for the package we\'re building, w/o the debian extensions')
    parser.add_argument('--working', help='A scratch build path. Default: %(default)s', default='/tmp/catkin_gbp')
    parser.add_argument('--output', help='The result of source deb building will go here. Default: %(default)s', default='/tmp/catkin_debs')
    parser.add_argument('--repo-fqdn', dest='repo_fqdn', help='The fully qualified domain name of the repo machine. Default: %(default)s', default='50.28.27.175')
    parser.add_argument('--repo-path', dest='repo_path', help='The path to find the repo on the machine. Default: %(default)s', default='/var/www/repos/building')
    parser.add_argument('-n', dest='noupload', help='Do not try to upload', action='store_true', default=False)
    
    args = parser.parse_args()

    return args

def make_working(working_dir):
    if not os.path.exists(working_dir):
        os.makedirs(working_dir)

def call(working_dir, command, pipe=None):
    print('+ cd %s && ' % working_dir + ' '.join(command))
    process = Popen(command, stdout=pipe, stderr=pipe, cwd=working_dir)
    output, unused_err = process.communicate()
    retcode = process.poll()
    if retcode:
        raise CalledProcessError(retcode, command)
    if pipe:
        return output

def check_local_repo_exists(repo_path):
    return os.path.exists(os.path.join(repo_path, '.git'))

def update_repo(working_dir, repo_path, repo_uri):
    if check_local_repo_exists(repo_path):
        print(repo_path)
        command = ('git', 'fetch', '--all')
        call(repo_path, command)
    else:
        command = ('gbp-clone', repo_uri)
        call(working_dir, command)

def verify_debian_tag(repo_path, package_name, package_version, distro):
    tags = call(repo_path, ('git', 'tag', '-l', 'debian/*'), pipe=subprocess.PIPE)

    expected_tag = 'debian/%s_%s_%s'%(package_name, package_version, distro)
    tag_list = tags.split('\n')

    if expected_tag in tag_list:
        return expected_tag
    else:
        print("No matching tag found. Are you sure you pointed to the right repository or the version is right?, expected %s:\n Tags: %s"%(expected_tag, tags))
    return None

def build_source_deb(repo_path, tag, output, upstream_branch=None):
    call(repo_path, ('git', 'checkout', tag))
    cmd = ['git', 'buildpackage', '--git-export-dir=%s' % output, '--git-ignore-new', '-S', '-uc', '-us', '--lintian-opts', '--suppress-tags', 'newer-standards-version']
    if upstream_branch is not None:
        cmd.append('--git-upstream-tree=branch')
        cmd.append('--git-upstream-branch=%s' % upstream_branch)
    call(repo_path, cmd)
    print("Successfully created changes in %s"%output)
    call(repo_path, ['ls', output])

def remove_upstream_source(distro, repo_fqdn, repo_path, package):
    # clear existing debs if they exits
    cmd = ['ssh', 'rosbuild@%(repo_fqdn)s' %locals(), '--',"( flock 200; /usr/bin/reprepro -b %(repo_path)s --ignore=emptyfilenamepart -V -T dsc removefilter %(distro)s \"Package (== %(package)s ) \" ) 200>%(repo_path)s/lock" %locals()]
    call('/tmp/', cmd)
    

def upload_source_deb(distro, repo_fqdn, repo_path, changesfile, packagename):


    upload_dir="/tmp/upload/%s"%packagename
    upload_source = os.path.dirname(changesfile)
    cmd = ("ssh rosbuild@%s -- mkdir -p %s"%(repo_fqdn, upload_dir)).split()
    call('/tmp/', cmd)
    cmd = "scp -r %s/*%s* rosbuild@%s:%s"%(upload_source, distro, repo_fqdn, upload_dir)).split()
    call('/tmp/', cmd)

    cmd = ("ssh rosbuild@%(repo_fqdn)s -- PYTHONPATH=/home/rosbuild/reprepro_updater/src python /home/rosbuild/reprepro_updater/scripts/include_folder.py -d %(distro)s -a source -f %(upload_dir) -p %(changesfile)s -c --delete --invalidate"%locals()).split()
    call('/tmp/', cmd)


def find_file(directory, extension, substring=''):
    """ Return the first file in directory which has extension and contains the substring """
    files = os.listdir(directory)
    for f in files:
        if extension == os.path.splitext(f)[1] and substring in f:
            return f
    return None
    


if __name__ == "__main__":
    args = parse_options()
    make_working(args.working)

    rd = rosdistro.Rosdistro(args.rosdistro)

    package_version = rd.get_version(args.short_package_name)
    print ("package name", args.short_package_name, "version", package_version)

    repo_base, extension = os.path.splitext(os.path.basename(args.repo_uri))
    repo_path = os.path.join(args.working, repo_base)

    update_repo(working_dir=args.working, repo_path=repo_path, repo_uri=args.repo_uri)


    report_failure = False
    for d in rd.get_target_distros():

        tag = verify_debian_tag(repo_path, args.package_name, package_version, d)
        if not tag:
            print("No tag; bailing")
            report_failure = True
            continue


        try:
            upstream_branch = None
            if args.rosdistro != 'fuerte':
                upstream_branch = 'release/%s/%s' % (args.short_package_name, package_version)
            build_source_deb(repo_path, tag, args.output, upstream_branch)
            print("successfully created sourcedeb for tag %s on repo %s."%(tag, repo_path))
        except CalledProcessError, ex:
            print("Failed to build source deb for tag %s on repo %s: %s"%(tag, repo_path, ex))
            report_failure = True
            continue

            
        try:
            changes_file = find_file(args.output, '.changes', d)
            print("Changes file is %s" % changes_file) 

            if args.noupload:
                print("Noupload argument passed, skipping upload of %s" % changes_file)
                continue

            print(os.listdir(args.output))

            # remove upstream so it doesn't error if we're downgrading
            remove_upstream_source(d, args.repo_fqdn, args.repo_path, args.package_name)

            upload_source_deb(d, args.repo_fqdn, args.repo_path, 
                              os.path.join(args.output, 
                                           changes_file),
                              args.working
                              )
            print("Succeeded uploading for distro %s."%(d))
        except CalledProcessError, ex:
            print("Failed uploading for distro %s: %s"%(d, ex))
            report_failure = True
            continue

    if report_failure:
        print("Errors have occurred in the source build see above. ")
        sys.exit(1)
