#!/bin/bash

distro=groovy

repos[0]=ros@http://50.28.27.175/repos/building
repos[1]=shadow@http://packages.ros.org/ros-shadow-fixed/ubuntu/
repos[2]=shadow@http://packages.ros.org/ros/ubuntu/

tables[0]=building
tables[1]=testing
tables[2]=public

# Update the database
db=${distro}_status.db
for i in 0 1 2; do
    repo_status_update_db.py --rosdistro=${distro} --substring=ros-${distro} -u --repo=${repos[i]} --sqlite3_db=$db --table=${tables[i]}
done

